image: node:latest

stages:
  - deploy

production:
  stage: deploy
  only:
      - master
  before_script:
    # - npm config set prefix /usr/local
    - npm install -g serverless
  script:
    - serverless deploy --stage production --verbose
  artifacts:
    paths:
    - .serverless
  environment: production

production:
  stage: deploy
  only:
      - dev
  before_script:
    # - npm config set prefix /usr/local
    - npm install -g serverless
  script:
    - serverless deploy --stage dev --verbose
  artifacts:
    paths:
    - .serverless
  environment: development