image: node:latest

stages:
  - deploy

production:
  stage: deploy
  only:
      refs:
        - master
      variables:
        - $CI_COMMIT_MESSAGE =~ /trigger ci/
  before_script:
    # - npm config set prefix /usr/local
    - npm install
    - npm install -g serverless
  script:
    - serverless deploy --stage production --verbose
  cache:
     paths:
       - node_modules/
  artifacts:
    paths:
    - .serverless
  environment: production

production:
  stage: deploy
  only:
      refs:
        - dev
      variables:
        - $CI_COMMIT_MESSAGE =~ /trigger ci/
  before_script:
    # - npm config set prefix /usr/local
    - npm install
    - npm install -g serverless
  script:
    - serverless deploy --stage dev --verbose
  cache:
     paths:
       - node_modules/
  artifacts:
    paths:
    - .serverless
  environment: development